// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM9iNVuTSWmpT5RF6sn400Dgk0N51Dx2I',
    appId: '1:928370354188:web:9a47631ac78dd4f8d32629',
    messagingSenderId: '928370354188',
    projectId: 'dailynews-5a27b',
    authDomain: 'dailynews-5a27b.firebaseapp.com',
    storageBucket: 'dailynews-5a27b.firebasestorage.app',
    measurementId: 'G-C4M3YBMMK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtK8nXDNNoh7uOnIWz3XDwsV2ozxpay_8',
    appId: '1:928370354188:android:9c82960748e51008d32629',
    messagingSenderId: '928370354188',
    projectId: 'dailynews-5a27b',
    storageBucket: 'dailynews-5a27b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrRUpJLkEAjoi8KDlfn_qKTvQ7sZAVQkQ',
    appId: '1:928370354188:ios:9c0d9edcc43769f6d32629',
    messagingSenderId: '928370354188',
    projectId: 'dailynews-5a27b',
    storageBucket: 'dailynews-5a27b.firebasestorage.app',
    iosBundleId: 'com.example.dailyNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrRUpJLkEAjoi8KDlfn_qKTvQ7sZAVQkQ',
    appId: '1:928370354188:ios:9c0d9edcc43769f6d32629',
    messagingSenderId: '928370354188',
    projectId: 'dailynews-5a27b',
    storageBucket: 'dailynews-5a27b.firebasestorage.app',
    iosBundleId: 'com.example.dailyNews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM9iNVuTSWmpT5RF6sn400Dgk0N51Dx2I',
    appId: '1:928370354188:web:da81a24c0b7740e2d32629',
    messagingSenderId: '928370354188',
    projectId: 'dailynews-5a27b',
    authDomain: 'dailynews-5a27b.firebaseapp.com',
    storageBucket: 'dailynews-5a27b.firebasestorage.app',
    measurementId: 'G-WB06Z1HX81',
  );
}
